### ISSUE TITLE
Feature Request: Seamlessly switch between zlib-x.x.x and zlib-ng.

### ISSUE THREAD

**Issue by JeffreyO** [jimmy-park/zlib-cmake#9]
Is it possible to add a feature to choose which zlib flavor you want to use and rename everything to just 'zlib'? So that projects can be transparently switched over to a faster zlib-ng flavor without losing the ability to use the regular zlib flavor?

**Comment by jimmy-park** [comment]
I think `zlib-ng`'s CMake support is well maintained.
If you want `zlib-ng`, just import that. You don't actually need this project.

If you really want to switch between them, how about this way?

```cmake
if(ZLIB_USE_NG)
    FetchContent_Declare(
        zlib-ng
        URL https://github.com/zlib-ng/zlib-ng/archive/2.2.1.zip
    )
    FetchContent_MakeAvailable(zlib-ng)
else()
    FetchContent_Declare(
        zlib-cmake
        URL https://github.com/jimmy-park/zlib-cmake/archive/1.3.1.zip
    )
    FetchContent_MakeAvailable(zlib-cmake)
endif()
```
